trigger:
  - master

pr:
  - master

variables:
  - name: CMAKE_VERSION
    value: 3.31.6
  - name: NDK_VERSION
    value: 28.2.13676358
  - name: UNITY_BUILD
    value: true
  - name: XCODE_VERSION
    value: 16.4

jobs:
  # Only run sanitizer jobs to verify the ASAN test catches the bug.
  - template: .github/jobs/macos.yml
    parameters:
      name: MacOS_Sanitizers
      vmImage: macOS-latest
      enableSanitizers: true

  - template: .github/jobs/win32.yml
    parameters:
      name: Win32_x64_D3D11_Sanitizers
      vmImage: windows-latest
      platform: x64
      enableSanitizers: true
