# BabylonScripts specific trigger
pr:
  branches:
    include:
    - master
  paths:
    include:
    - Apps\BabylonScripts\babylon.max.js
    - Apps\BabylonScripts\babylon.gui.js
    - Apps\BabylonScripts\babylonjs.materials.js
    - Apps\BabylonScripts\babylonjs.package.json

jobs:
- job: BabylonScripts
  timeoutInMinutes: 15
  pool:
    vmImage: 'windows-latest'

  steps:
  - script: |
      git submodule update --init --recursive
    displayName: 'Checkout dependencies'

- task: PowerShell@2
  inputs:
    filePath: $(System.DefaultWorkingDirectory)\Apps\BabylonScripts\ValidateFilesExistInLatestNPMPackages.ps1
  displayName: 'Validate Files Exist in Latest npm Packages'