if(EXISTS "${CMAKE_CURRENT_BINARY_DIR}/Dependencies/bgfx.cmake/RelWithDebInfo/bgfx.lib")
    set(BGFX_DIR "${CMAKE_CURRENT_SOURCE_DIR}/Dependencies/bgfx.cmake/bgfx" CACHE STRING "Location of bgfx." )
    set(BIMG_DIR "${CMAKE_CURRENT_SOURCE_DIR}/Dependencies/bgfx.cmake/bimg" CACHE STRING "Location of bimg." )
    set(BX_DIR "${CMAKE_CURRENT_SOURCE_DIR}/Dependencies/bgfx.cmake/bx" CACHE STRING "Location of bx." )

    add_library(bgfx STATIC IMPORTED GLOBAL)
    set_property(TARGET bgfx PROPERTY IMPORTED_LOCATION "${CMAKE_CURRENT_BINARY_DIR}/Dependencies/bgfx.cmake/RelWithDebInfo/bgfx.lib")
    target_include_directories(bgfx INTERFACE "${BGFX_DIR}/include")

    add_library(bx STATIC IMPORTED GLOBAL)
    set_property(TARGET bx PROPERTY IMPORTED_LOCATION "${CMAKE_CURRENT_BINARY_DIR}/Dependencies/bgfx.cmake/RelWithDebInfo/bx.lib")
    target_include_directories(bx INTERFACE "${BX_DIR}/include" "${BX_DIR}/include/compat/msvc")

    add_library(bimg STATIC IMPORTED GLOBAL)
    set_property(TARGET bimg PROPERTY IMPORTED_LOCATION "${CMAKE_CURRENT_BINARY_DIR}/Dependencies/bgfx.cmake/RelWithDebInfo/bimg.lib")
    target_include_directories(bimg INTERFACE "${BIMG_DIR}/include" )

    if (BGFX_CONFIG_DEBUG)
        target_compile_definitions( bgfx INTERFACE "BX_CONFIG_DEBUG=1" )
    else()
        target_compile_definitions( bgfx INTERFACE "BX_CONFIG_DEBUG=0" )
    endif()

    add_library(astc-encoder STATIC IMPORTED GLOBAL)
    set_property(TARGET astc-encoder PROPERTY IMPORTED_LOCATION "${CMAKE_CURRENT_BINARY_DIR}/Dependencies/bgfx.cmake/RelWithDebInfo/astc-encoder.lib")
    add_library(edtaa3 STATIC IMPORTED GLOBAL)
    set_property(TARGET edtaa3 PROPERTY IMPORTED_LOCATION "${CMAKE_CURRENT_BINARY_DIR}/Dependencies/bgfx.cmake/RelWithDebInfo/edtaa3.lib")
    add_library(etc1 STATIC IMPORTED GLOBAL)
    set_property(TARGET etc1 PROPERTY IMPORTED_LOCATION "${CMAKE_CURRENT_BINARY_DIR}/Dependencies/bgfx.cmake/RelWithDebInfo/etc1.lib")
    add_library(etc2 STATIC IMPORTED GLOBAL)
    set_property(TARGET etc2 PROPERTY IMPORTED_LOCATION "${CMAKE_CURRENT_BINARY_DIR}/Dependencies/bgfx.cmake/RelWithDebInfo/etc2.lib")
    add_library(iqa STATIC IMPORTED GLOBAL)
    set_property(TARGET iqa PROPERTY IMPORTED_LOCATION "${CMAKE_CURRENT_BINARY_DIR}/Dependencies/bgfx.cmake/RelWithDebInfo/iqa.lib")
    add_library(nvtt STATIC IMPORTED GLOBAL)
    set_property(TARGET nvtt PROPERTY IMPORTED_LOCATION "${CMAKE_CURRENT_BINARY_DIR}/Dependencies/bgfx.cmake/RelWithDebInfo/nvtt.lib")
    add_library(pvrtc STATIC IMPORTED GLOBAL)
    set_property(TARGET pvrtc PROPERTY IMPORTED_LOCATION "${CMAKE_CURRENT_BINARY_DIR}/Dependencies/bgfx.cmake/RelWithDebInfo/pvrtc.lib")
    add_library(squish STATIC IMPORTED GLOBAL)
    set_property(TARGET squish PROPERTY IMPORTED_LOCATION "${CMAKE_CURRENT_BINARY_DIR}/Dependencies/bgfx.cmake/RelWithDebInfo/squish.lib")
    add_library(tinyexr STATIC IMPORTED GLOBAL)
    set_property(TARGET tinyexr PROPERTY IMPORTED_LOCATION "${CMAKE_CURRENT_BINARY_DIR}/Dependencies/bgfx.cmake/RelWithDebInfo/tinyexr.lib")

    target_link_libraries(bimg INTERFACE astc-encoder edtaa3 etc1 etc2 iqa nvtt pvrtc squish tinyexr)

    set(bgfx_CACHED_BUILD true GLOBAL)
    message("Using bgfx cache build")
endif()