function(on_linked_as_dependency target)
    if (NAPI_JAVASCRIPT_ENGINE STREQUAL "V8")
        propagate_on_linked_as_dependency_cmake_file(napi ${target})
    
        get_target_property(type ${target} TYPE)
        if(${type} STREQUAL "EXECUTABLE")
            if (WINDOWS_STORE)
                target_sources(${target} PRIVATE ${NAPI_JAVASCRIPT_RUNTIME_OUTPUT_ARTIFACTS})
                set_property(SOURCE ${NAPI_JAVASCRIPT_RUNTIME_OUTPUT_ARTIFACTS} PROPERTY VS_DEPLOYMENT_CONTENT 1)
                set_property(SOURCE ${NAPI_JAVASCRIPT_RUNTIME_OUTPUT_ARTIFACTS} PROPERTY VS_DEPLOYMENT_LOCATION ".")
            else()
                foreach(artifact ${NAPI_JAVASCRIPT_RUNTIME_OUTPUT_ARTIFACTS})
                    add_custom_command(TARGET ${target} POST_BUILD COMMAND ${CMAKE_COMMAND} -E copy_if_different ${artifact} $<TARGET_FILE_DIR:${target}>)
                endforeach(artifact)
            endif()
        endif()
    endif()
endfunction()
