function(on_after_link target)
    get_target_property(type ${target} TYPE)
    if(${type} STREQUAL "EXECUTABLE")
        if (WINDOWS_STORE)
            set_property(SOURCE ${BABYLON_NATIVE_DEPENDENCIES} PROPERTY VS_DEPLOYMENT_CONTENT 1)
            set_property(SOURCE ${BABYLON_NATIVE_DEPENDENCIES} PROPERTY VS_DEPLOYMENT_LOCATION ".")
        else()
            foreach(artifact ${NAPI_JAVASCRIPT_RUNTIME_OUTPUT_ARTIFACTS})
                add_custom_command(TARGET ${target} POST_BUILD COMMAND ${CMAKE_COMMAND} -E copy_if_different ${artifact} $<TARGET_FILE_DIR:${target}>)
            endforeach(artifact)
        endif()
    endif()
endfunction()
