parameters:
  name: ''
  vmImage: ''
  JSEngine: ''
  macOSCodename: ''

jobs:
  - job: ${{ parameters.name }}
    timeoutInMinutes: 45
    pool:
      vmImage: ${{ parameters.vmImage }}

    variables:
      SANITIZER_FLAG: ${{ if eq(parameters.Sanitizers, true) }}'ON'${{ else }}'OFF'${{ endif }}

    steps:
    - template: cmake.yml
      parameters:
        vmImage: ${{ parameters.vmImage }}

    - task: JavaToolInstaller@0
      inputs:
        versionSpec: '17'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'

    - task: Gradle@3
      inputs:
          workingDirectory: 'Apps/Playground/Android'
          gradleWrapperFile: 'Apps/Playground/Android/gradlew'
          gradleOptions: '-Xmx1536m'
          options: '-PJSEngine=${{ parameters.JSEngine }} -PARM64Only -PNDK_VERSION=$(NDK_VERSION) -PSANITIZERS=$(SANITIZER_FLAG)'
          publishJUnitResults: false
          tasks: 'assembleRelease'
      displayName: 'Build Playground ${{ parameters.JSEngine }}'
