parameters:
  name: ''
  vmImage: ''
  JSEngine: ''
  macOSCodename: ''

jobs:
  - job: ${{ parameters.name }}
    timeoutInMinutes: 45
    pool:
      vmImage: ${{ parameters.vmImage }}
      
    steps:
    - template: cmake.yml
      parameters:
        vmImage: ${{ parameters.vmImage }}

    - task: Gradle@2
      inputs:
          workingDirectory: 'Apps/Playground/Android'
          gradleWrapperFile: 'Apps/Playground/Android/gradlew'
          gradleOptions: '-Xmx1536m'
          options: '-PJSEngine=${{ parameters.JSEngine }} -PARM64Only -PNDK_VERSION=$(NDK_VERSION)'
          publishJUnitResults: false
          tasks: 'assembleRelease'
      displayName: 'Build Playground ${{ parameters.JSEngine }}'
