parameters:
  name: ''
  vmImage: ''
  JSEngine: ''
  macOSCodename: ''

jobs:
  - job: ${{ parameters.name }}
    timeoutInMinutes: 45
    pool:
      vmImage: ${{ parameters.vmImage }}
      
    steps:
    - script: |
        git submodule update --init --recursive
      displayName: 'Checkout dependencies'

    - task: Npm@1
      inputs:
        command: 'install'
        workingDir: 'Apps'
      displayName: 'Install Babylon.js NPM packages'

    - template: cmake.yml
      parameters:
        vmImage: ${{ parameters.vmImage }}

    - script: |
        cd Apps/Playground/Android
        npm install
        cd ../../ValidationTests/Android
        npm install
      displayName: 'Install JS engine NPMs'

    - task: Gradle@2
      inputs:
          workingDirectory: 'Apps/Playground/Android'
          gradleWrapperFile: 'Apps/Playground/Android/gradlew'
          gradleOptions: '-Xmx1536m'
          options: '-PJSEngine=${{ parameters.JSEngine }} -PARM64Only -PNDK_VERSION=$(NDK_VERSION)'
          publishJUnitResults: false
          tasks: 'assembleRelease'
      displayName: 'Build Playground ${{ parameters.JSEngine }}'

    - task: Gradle@2
      inputs:
          workingDirectory: 'Apps/ValidationTests/Android'
          gradleWrapperFile: 'Apps/ValidationTests/Android/gradlew'
          gradleOptions: '-Xmx1536m'
          options: '-PJSEngine=${{ parameters.JSEngine }} -PARM64Only -PNDK_VERSION=$(NDK_VERSION)'
          publishJUnitResults: false
          tasks: 'assembleRelease'
      displayName: 'Build ValidationTests ${{ parameters.JSEngine }}'