parameters:
  name: ''
  vmImage: ''
  xcodeVersion: ''
  deploymentTarget: '12'

jobs:
  - job: ${{ parameters.name }}
    timeoutInMinutes: 30
    pool:
      vmImage: ${{ parameters.vmImage }}
  
    steps:
    - template: cmake.yml
      parameters:
        vmImage: ${{ parameters.vmImage }}

    - script: |
        sudo xcode-select --switch /Applications/Xcode_${{ parameters.xcodeVersion }}.app/Contents/Developer
      displayName: 'Select Xcode ${{ parameters.xcodeVersion }}'

    - script: |
        mkdir buildiOS
        cd buildiOS
        cmake .. -G Xcode -D IOS=ON -D DEPLOYMENT_TARGET=${{ parameters.deploymentTarget }} -D CMAKE_UNITY_BUILD=$(UNITY_BUILD)
      displayName: 'Generate iOS solution'

    - task: Xcode@5
      inputs:
        xcWorkspacePath: 'buildiOS/BabylonNative.xcodeproj'
        scheme: 'Playground'
        sdk: 'iphoneos'
        useXcpretty: false
        configuration: RelWithDebInfo
      displayName: 'Build Playground iOS'

    - task: Xcode@5
      inputs:
        xcWorkspacePath: 'buildiOS/BabylonNative.xcodeproj'
        scheme: 'install'
        sdk: 'iphoneos'
        useXcpretty: false
        configuration: Release
      displayName: 'Build Installation content iOS'

    - script: |
        cmake --install buildiOS --prefix="$(Build.Repository.LocalPath)/install"
      displayName: 'Install into $(Build.Repository.LocalPath)/install'

