parameters:
  name: ''
  vmImage: ''
  xcodeVersion: ''
  deploymentTarget: '12'

jobs:
  - job: ${{ parameters.name }}
    timeoutInMinutes: 30
    pool:
      vmImage: ${{ parameters.vmImage }}
  
    steps:
    - template: cmake.yml
      parameters:
        vmImage: ${{ parameters.vmImage }}

    - script: |
        sudo xcode-select --switch /Applications/Xcode_${{ parameters.xcodeVersion }}.app/Contents/Developer
      displayName: 'Select Xcode ${{ parameters.xcodeVersion }}'

    - script: |
        cmake -S .. -G Xcode -B buildiOS -D IOS=ON -D DEPLOYMENT_TARGET=${{ parameters.deploymentTarget }} -D CMAKE_UNITY_BUILD=$(UNITY_BUILD) -D BABYLON_NATIVE_PLUGIN_NATIVETRACING=OFF
      displayName: 'Generate iOS solution'

    - task: Xcode@5
      inputs:
        xcWorkspacePath: 'buildiOS/BabylonNative.xcodeproj'
        scheme: 'Playground'
        sdk: 'iphoneos'
        useXcpretty: false
        configuration: Release
      displayName: 'Build Playground iOS'

    - script: |
        cmake --install buildiOS --prefix="$(Build.SourcesDirectory)/install"
        lipo -info $(Build.SourcesDirectory)/Install/lib/libxr.a
      displayName: 'Install'

