parameters:
  name: ''
  vmImage: ''
  xCodeVersion: ''
  macOSCodename: ''
  deploymentTarget: '12'

jobs:
  - job: ${{ parameters.name }}
    timeoutInMinutes: 30
    pool:
      vmImage: ${{ parameters.vmImage }}
  
    steps:
    - script: |
        git submodule update --init --recursive
      displayName: 'Checkout dependencies'

    - template: cmake.yml
      parameters:
        vmImage: ${{ parameters.vmImage }}

    - script: |
        sudo xcode-select --switch /Applications/Xcode_${{ parameters.xCodeVersion }}.app/Contents/Developer
      displayName: 'Select XCode ${{ parameters.xCodeVersion }}'

    - script: |
        mkdir buildiOS
        cd buildiOS
        cmake .. -G Xcode -DCMAKE_TOOLCHAIN_FILE=../Dependencies/ios-cmake/ios.toolchain.cmake -DPLATFORM=OS64COMBINED -DENABLE_ARC=0 -DDEPLOYMENT_TARGET=${{ parameters.deploymentTarget }} -DENABLE_GLSLANG_BINARIES=OFF -DSPIRV_CROSS_CLI=OFF -DCMAKE_UNITY_BUILD=${UNITY_BUILD}
      displayName: 'Generate iOS solution'

    - task: Xcode@5
      inputs:
        xcWorkspacePath: 'buildiOS/BabylonNative.xcodeproj'
        scheme: 'Playground'
        sdk: 'iphoneos'
        useXcpretty: false
        configuration: RelWithDebInfo
      displayName: 'Build Playground iOS'

