parameters:
  name: ''
  vmImage: ''
  CC: ''
  CXX: ''
  JSEngine: ''

jobs:
  - job: ${{ parameters.name }}
    timeoutInMinutes: 30
    pool:
      vmImage: ${{ parameters.vmImage }}

    variables:
      CC: ${{ parameters.CC }}
      CXX: ${{ parameters.CXX }}
  
    steps:
    - template: cmake.yml
      parameters:
        vmImage: ${{ parameters.vmImage }}

    - script: |
        sudo apt-get update
        sudo apt-get install libjavascriptcoregtk-4.1-dev libgl1-mesa-dev libcurl4-openssl-dev libwayland-dev
      displayName: 'Install packages'

    - script: |
        cmake -G Ninja -B build -D JAVASCRIPTCORE_LIBRARY=/usr/lib/x86_64-linux-gnu/libjavascriptcoregtk-4.1.so -D NAPI_JAVASCRIPT_ENGINE=${{ parameters.JSEngine }} -D CMAKE_BUILD_TYPE=RelWithDebInfo -D BX_CONFIG_DEBUG=ON -D CMAKE_UNITY_BUILD=$(UNITY_BUILD) -D OpenGL_GL_PREFERENCE=GLVND -D BABYLON_DEBUG_TRACE=ON
        ninja -C build
      displayName: 'Build X11'
    
#    - script: |
#        export DISPLAY=:99
#        Xvfb :99 -screen 0 1600x900x24 &
#        sleep 3
#        cd build/Apps/ValidationTests
#        ./ValidationTests
#      # Only test with V8 for now as ValidationTests with JSC are pretty unstable
#      condition: contains('${{ parameters.JSEngine }}', 'V8')
#      displayName: 'Validation Tests'
#
#    - task: PublishBuildArtifacts@1
#      inputs:
#        artifactName: '${{ parameters.name }} Rendered Pictures'
#        pathtoPublish: 'build/Apps/Playground/Results'
#      displayName: 'Publish Tests ${{ parameters.name }} Results'
#      condition: always()
#    - task: PublishBuildArtifacts@1
#      inputs:
#        artifactName: '${{ parameters.name }} Error Pictures'
#        pathtoPublish: 'build/Apps/Playground/Errors'
#      displayName: 'Publish Tests ${{ parameters.name }} Errors'
#      condition: failed()

    - script: |
        export DISPLAY=:99
        Xvfb :99 -screen 0 1600x900x24 &
        while [ ! -e /tmp/.X11-unix/X99 ]; do sleep 0.1; done
        cd build/Apps/UnitTests
        ./UnitTests
      displayName: 'Unit Tests'