parameters:
  name: ''
  vmImage: ''

jobs:
  - job: ${{ parameters.name }}
    timeoutInMinutes: 30
    pool:
      vmImage: ${{ parameters.vmImage }}

    variables:
      SANITIZER_FLAG: ${{ if eq(parameters.Sanitizers, true) }}'ON'${{ else }}'OFF'${{ endif }}

    steps:
    - template: cmake.yml
      parameters:
        vmImage: ${{ parameters.vmImage }}

    - script: |
        sudo xcode-select --switch /Applications/Xcode_$(XCODE_VERSION).app/Contents/Developer
      displayName: 'Select XCode $(XCODE_VERSION)'

    - script: |
        cmake -G Xcode -B buildmacOS -D CMAKE_UNITY_BUILD=$(UNITY_BUILD) -D BABYLON_DEBUG_TRACE=ON -D ENABLE_SANITIZERS=$(SANITIZER_FLAG)
      displayName: 'Generate macOS solution'

    - script: |
        xcodebuild -list -project buildmacOS/BabylonNative.xcodeproj
      displayName: 'List available project schemes'

    - task: Xcode@5
      inputs:
        xcWorkspacePath: 'buildmacOS/BabylonNative.xcodeproj'
        scheme: 'Playground'
        sdk: 'macosx'
        useXcpretty: false
        configuration: RelWithDebInfo
      displayName: 'Build Playground macOS'

    - task: Xcode@5
      inputs:
        xcWorkspacePath: 'buildmacOS/BabylonNative.xcodeproj'
        scheme: 'UnitTests'
        sdk: 'macosx'
        useXcpretty: false
        configuration: RelWithDebInfo
      displayName: 'Build UnitTests macOS'

    - script: |
        cd buildmacOS/Apps/UnitTests/RelWithDebInfo
        ./UnitTests
      displayName: 'Run UnitTests macOS'