parameters:
  name: ""
  vmImage: ""
  enableSanitizers: false
  generator: Xcode

jobs:
  - job: ${{parameters.name}}
    timeoutInMinutes: 30
    pool:
      vmImage: ${{parameters.vmImage}}

    variables:
      SANITIZER_FLAG: ${{coalesce(replace(format('{0}', parameters.enableSanitizers), 'True', 'ON'), 'OFF')}}

    steps:
      - template: cmake.yml
        parameters:
          vmImage: ${{parameters.vmImage}}

      - script: |
          sudo xcode-select --switch /Applications/Xcode_$(XCODE_VERSION).app/Contents/Developer
        displayName: "Select XCode $(XCODE_VERSION)"

      - script: |
          cmake -G "${{parameters.generator}}" -B build/macOS -D CMAKE_UNITY_BUILD=$(UNITY_BUILD) -D BABYLON_DEBUG_TRACE=ON -D ENABLE_SANITIZERS=$(SANITIZER_FLAG) -D BABYLON_NATIVE_TESTS_USE_NOOP_METAL_DEVICE=ON
        displayName: "Generate macOS solution"

      - script: |
          cmake --build build/macOS --target Playground --config RelWithDebInfo
        displayName: "Build Playground macOS"

      - script: |
          cmake --build build/macOS --target UnitTests --config RelWithDebInfo
        displayName: "Build UnitTests macOS"

      - script: |
          cd build/macOS/Apps/UnitTests/RelWithDebInfo
          ./UnitTests
        displayName: "Run UnitTests macOS"
