parameters:
  vmImage: ''

steps:
  - script: |
      brew uninstall cmake
      brew install ninja
      wget https://github.com/Kitware/CMake/releases/download/v$(CMAKE_VERSION)/cmake-$(CMAKE_VERSION)-macos-universal.tar.gz
      sudo mkdir -p /opt/cmake
      sudo tar xvzf cmake-$(CMAKE_VERSION)-macos-universal.tar.gz -C /opt/cmake
      sudo rm /usr/local/bin/cmake
      sudo ln -s /opt/cmake/cmake-$(CMAKE_VERSION)-macos-universal/CMake.app/contents/MacOS/CMake /usr/local/bin/cmake
      cmake --version
    displayName: 'CMake version'
    condition: contains('${{ parameters.vmImage }}', 'macOS')
