# BabylonScripts specific trigger
parameters:
  name: ''
  vmImage: ''
  
jobs:
- job: ${{ parameters.name }}
  timeoutInMinutes: 15
  pool:
    vmImage: ${{ parameters.vmImage }}

  steps:
  - script: |
      git submodule update --init --recursive
    displayName: 'Checkout dependencies'

- task: PowerShell@2
  inputs:
    filePath: $(System.DefaultWorkingDirectory)\Apps\BabylonScripts\ValidateFilesExistInLatestNPMPackages.ps1
  displayName: 'Validate Files Exist in Latest npm Packages'