parameters:
  name: ""
  vmImage: ""

jobs:
  - job: ${{parameters.name}}
    timeoutInMinutes: 20
    pool:
      vmImage: ${{parameters.vmImage}}

    steps:
      - template: cmake.yml
        parameters:
          vmImage: ${{parameters.vmImage}}

      - script: |
          sudo xcode-select --switch /Applications/Xcode_$(XCODE_VERSION).app/Contents/Developer
        displayName: "Select XCode $(XCODE_VERSION)"

      - script: |
          cmake -B build/macOS -G Xcode -D CMAKE_UNITY_BUILD=$(UNITY_BUILD) -D BABYLON_NATIVE_BUILD_APPS=OFF -D BABYLON_DEBUG_TRACE=ON
        displayName: "Configure"

      - script: |
          cmake --build build/macOS --config RelWithDebInfo
        displayName: "Build"

      - script: |
          cmake --install build/macOS --prefix=build/macOS/Install --config RelWithDebInfo
        displayName: "Install"
