parameters:
  - name: name
    type: string
  - name: vmImage
    type: string
  - name: graphics_api
    type: string
    default: D3D11

jobs:
  - job: ${{parameters.name}}
    timeoutInMinutes: 30
    pool:
      vmImage: ${{parameters.vmImage}}

    steps:
      - template: cmake.yml
        parameters:
          vmImage: ${{parameters.vmImage}}

      - script: |
          cmake -B build/Win32 -G "Visual Studio 17 2022" -D CMAKE_UNITY_BUILD=$(UNITY_BUILD) -D BABYLON_NATIVE_BUILD_APPS=OFF -D BABYLON_DEBUG_TRACE=ON
        displayName: "Configure"

      - script: |
          cmake --build build/Win32 --config RelWithDebInfo
        displayName: "Build"

      - script: |
          cmake --install build/Win32 --prefix=build/Win32/Install --config RelWithDebInfo
        displayName: "Install"

      - script: |
          cmake Install/Test -B build/TestInstall -D INSTALL_DIR=$(Build.SourcesDirectory)/build/Win32/Install
          cmake --build build/TestInstall --config RelWithDebInfo
        displayName: "Test Install"
