parameters:
  name: ""
  vmImage: ""
  CC: ""
  CXX: ""

jobs:
  - job: ${{parameters.name}}
    #condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    timeoutInMinutes: 30
    pool:
      vmImage: ${{parameters.vmImage}}

    variables:
      CC: ${{parameters.CC}}
      CXX: ${{parameters.CXX}}

    steps:
      - template: cmake.yml
        parameters:
          vmImage: ${{parameters.vmImage}}

      - script: |
          sudo apt-get update
          sudo apt-get install libjavascriptcoregtk-4.1-dev libgl1-mesa-dev libcurl4-openssl-dev libwayland-dev
        displayName: "Install packages"

      - script: |
          cmake -B build -G Ninja -D CMAKE_BUILD_TYPE=RelWithDebInfo -D CMAKE_UNITY_BUILD=$(UNITY_BUILD) -D BABYLON_NATIVE_BUILD_APPS=OFF -D BABYLON_DEBUG_TRACE=ON
        displayName: "Configure"

      - script: |
          cmake --build build --config RelWithDebInfo
        displayName: "Build"

      - script: |
          cmake --install build --prefix=build/Install --config=RelWithDebInfo
        displayName: "Install"
