parameters:
  name: ''
  vmImage: ''
  deploymentTarget: '15'

jobs:
  - job: ${{ parameters.name }}
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    timeoutInMinutes: 60
    pool:
      vmImage: ${{ parameters.vmImage }}
  
    steps:
    - template: cmake.yml
      parameters:
        vmImage: ${{ parameters.vmImage }}

    - script: |
        sudo xcode-select --switch /Applications/Xcode_$(XCODE_VERSION).app/Contents/Developer
      displayName: 'Select Xcode $(XCODE_VERSION)'

    - script: |
        cmake -G Xcode -B buildiOS -D IOS=ON -D DEPLOYMENT_TARGET=${{ parameters.deploymentTarget }} -D CMAKE_UNITY_BUILD=$(UNITY_BUILD) -D BABYLON_DEBUG_TRACE=ON -D CMAKE_IOS_INSTALL_COMBINED=NO
      displayName: 'Generate iOS solution'

    # Replaced Xcode task with cmake command instead because of 'unable to attach DB: error: accessing build database'
    # Some context and (non working) workarounds here : https://stackoverflow.com/questions/73301738/xcode-13-4-1-error-unable-to-attach-db-error-accessing-build-database-react/73301739
    - script: |
        cmake --build buildiOS --config Release -- -sdk iphoneos CODE_SIGNING_ALLOWED=NO
      displayName: 'Build iOS solution'

    - script: |
        cmake --install buildiOS --prefix="$(Build.SourcesDirectory)/Install"
        lipo -info $(Build.SourcesDirectory)/Install/lib/libxr.a
      displayName: 'Install'

