parameters:
  name: ""
  vmImage: ""

jobs:
  - job: ${{parameters.name}}
    #condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    timeoutInMinutes: 30
    pool:
      vmImage: ${{parameters.vmImage}}

    steps:
      - template: cmake.yml
        parameters:
          vmImage: ${{parameters.vmImage}}

      - script: |
          sudo xcode-select --switch /Applications/Xcode_$(XCODE_VERSION).app/Contents/Developer
        displayName: "Select XCode $(XCODE_VERSION)"

      - script: |
          cmake -B build -G Xcode -D CMAKE_UNITY_BUILD=$(UNITY_BUILD) -D BABYLON_NATIVE_BUILD_APPS=OFF -D BABYLON_DEBUG_TRACE=ON
        displayName: "Configure"

      - script: |
          cmake --build build --config RelWithDebInfo
        displayName: "Build"

      - script: |
          cmake --install build --prefix=build/Install --config RelWithDebInfo
        displayName: "Install"
