parameters:
- name: name
  type: string
- name: vmImage
  type: string
- name: platform
  type: string
- name: napiType
  type: string
  default: direct
  values:
  - direct
  - jsi


jobs:
  - job: ${{ parameters.name }}
    timeoutInMinutes: 30
    pool:
      vmImage: ${{ parameters.vmImage }}
    variables:
      ${{ if eq(parameters.napiType, 'jsi') }}:
        napiSuffix: '_jsi'
        jsEngineDefine: '-DNAPI_JAVASCRIPT_ENGINE=JSI'
      ${{ if ne(parameters.napiType, 'jsi') }}:
        napiSuffix: ''
        jsEngineDefine: ''
      
    steps:
    - script: |
        git submodule update --init --recursive
      displayName: 'Checkout dependencies'
    
    - task: Npm@1
      inputs:
        command: 'install'
        workingDir: 'Apps'
      displayName: 'Install Babylon.js NPM packages'

    - script: |
        mkdir buildUWP_${{ parameters.platform }}$(napiSuffix)
        cd buildUWP_${{ parameters.platform }}$(napiSuffix)
        cmake .. -DCMAKE_SYSTEM_NAME=WindowsStore -DCMAKE_SYSTEM_VERSION=10.0 $(jsEngineDefine) -A ${{ parameters.platform }}
      displayName: 'Generate UWP_${{ parameters.platform }}$(napiSuffix) solution'
  
    - task: VSBuild@1
      inputs:
        solution: 'buildUWP_${{ parameters.platform }}$(napiSuffix)/BabylonNative.sln'
        maximumCpuCount: true
        configuration: 'RelWithDebInfo'
        msbuildArgs: '/p:AppxPackageSigningEnabled=false'
      displayName: 'Build UWP_${{ parameters.platform }}$(napiSuffix)'
