name: Build macOS

on:
  workflow_call:
    inputs:
      generator:
        required: false
        type: string
        default: Xcode
      enable-sanitizers:
        required: false
        type: boolean
        default: false
      xcode-version:
        required: false
        type: string
        default: '16.4'
      runs-on:
        required: false
        type: string
        default: macos-latest

env:
  UBSAN_OPTIONS: halt_on_error=1:print_stacktrace=1:symbolize=1
  ASAN_OPTIONS: abort_on_error=1

jobs:
  build:
    runs-on: ${{ inputs.runs-on }}
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v5


      - name: Select Xcode ${{ inputs.xcode-version }}
        run: sudo xcode-select --switch /Applications/Xcode_${{ inputs.xcode-version }}.app/Contents/Developer

      - name: Generate macOS solution
        run: |
          cmake -G "${{ inputs.generator }}" -B build/macOS \
            -D BABYLON_DEBUG_TRACE=ON \
            -D ENABLE_SANITIZERS=${{ inputs.enable-sanitizers && 'ON' || 'OFF' }} \
            -D BABYLON_NATIVE_TESTS_USE_NOOP_METAL_DEVICE=ON

      - name: Build Playground macOS
        run: cmake --build build/macOS --target Playground --config RelWithDebInfo

      - name: Build UnitTests macOS
        run: cmake --build build/macOS --target UnitTests --config RelWithDebInfo

      - name: Build ModuleLoadTest macOS
        run: cmake --build build/macOS --target ModuleLoadTest --config RelWithDebInfo

      - name: Enable Core Dump
        run: sudo sysctl -w kern.corefile=%N.core.%P

      - name: Run UnitTests macOS
        run: |
          cd build/macOS/Apps/UnitTests/RelWithDebInfo
          ulimit -c unlimited
          ./UnitTests

      - name: Run ModuleLoadTest macOS
        if: ${{ !inputs.enable-sanitizers }}
        run: |
          cd build/macOS/Apps/ModuleLoadTest/RelWithDebInfo
          ulimit -c unlimited
          ./ModuleLoadTest

      - name: Upload UnitTests Core Dumps
        if: failure()
        uses: actions/upload-artifact@v6
        with:
          name: macos-${{ inputs.generator }}${{ inputs.enable-sanitizers && '-sanitizer' || '' }}-core-dumps
          path: |
            build/macOS/Apps/UnitTests/RelWithDebInfo/UnitTests
            build/macOS/Apps/UnitTests/RelWithDebInfo/*.core.*
