name: Build iOS

on:
  workflow_call:
    inputs:
      deployment-target:
        required: true
        type: string
      xcode-version:
        required: false
        type: string
        default: '16.4'
      runs-on:
        required: false
        type: string
        default: macos-latest

jobs:
  build:
    runs-on: ${{ inputs.runs-on }}
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v5


      - name: Select Xcode ${{ inputs.xcode-version }}
        run: sudo xcode-select --switch /Applications/Xcode_${{ inputs.xcode-version }}.app/Contents/Developer

      - name: Generate iOS solution
        run: |
          cmake -G Xcode -B build/iOS \
            -D IOS=ON \
            -D DEPLOYMENT_TARGET=${{ inputs.deployment-target }} \
            -D BABYLON_DEBUG_TRACE=ON \
            -D CMAKE_IOS_INSTALL_COMBINED=NO

      - name: Build Playground iOS
        run: |
          xcodebuild \
            -project build/iOS/BabylonNative.xcodeproj \
            -scheme Playground \
            -sdk iphoneos \
            -configuration Release \
            CODE_SIGNING_ALLOWED=NO
