name: Build Win32 Precompiled Shader Test

on:
  workflow_call:
    inputs:
      platform:
        required: false
        type: string
        default: x64

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v5


      - name: Generate solution
        shell: cmd
        run: |
          cmake -G "Visual Studio 17 2022" ^
            -B build/Win32_${{ inputs.platform }}_PrecompiledShaderTest ^
            -A ${{ inputs.platform }} ^
            -D BX_CONFIG_DEBUG=ON ^
            -D GRAPHICS_API=D3D11 ^
            -D BGFX_CONFIG_MAX_FRAME_BUFFERS=256 ^
            -D BABYLON_DEBUG_TRACE=ON ^
            -D BABYLON_NATIVE_PLUGIN_NATIVEENGINE_COMPILESHADERS=OFF

      - name: Build PrecompiledShaderTest
        shell: cmd
        run: |
          cmake --build build/Win32_${{ inputs.platform }}_PrecompiledShaderTest --config RelWithDebInfo --target PrecompiledShaderTest -- /m

      - name: Enable Crash Dump
        shell: cmd
        run: |
          reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps\PrecompiledShaderTest.exe" /f
          reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps\PrecompiledShaderTest.exe" /v DumpType /t REG_DWORD /d 2 /f
          reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps\PrecompiledShaderTest.exe" /v DumpCount /t REG_DWORD /d 1 /f
          reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps\PrecompiledShaderTest.exe" /v DumpFolder /t REG_SZ /d "%RUNNER_TEMP%\Dumps" /f

      - name: Run Precompiled Shader Test
        shell: cmd
        run: |
          cd build\Win32_${{ inputs.platform }}_PrecompiledShaderTest\Apps\PrecompiledShaderTest\RelWithDebInfo
          PrecompiledShaderTest

      - name: Upload Crash Dumps
        if: failure()
        uses: actions/upload-artifact@v6
        with:
          name: precompiled-shader-test-crash-dumps
          path: |
            build/Win32_${{ inputs.platform }}_PrecompiledShaderTest/Apps/PrecompiledShaderTest/RelWithDebInfo/PrecompiledShaderTest.*
            ${{ runner.temp }}/Dumps/
          if-no-files-found: ignore
