name: Test Install iOS

on:
  workflow_call:
    inputs:
      deployment-target:
        required: true
        type: string
      xcode-version:
        required: false
        type: string
        default: '16.4'

jobs:
  test-install:
    runs-on: macos-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v5


      - name: Select Xcode ${{ inputs.xcode-version }}
        run: sudo xcode-select --switch /Applications/Xcode_${{ inputs.xcode-version }}.app/Contents/Developer

      - name: Configure
        run: |
          cmake -B build/iOS -G Xcode \
            -D IOS=ON \
            -D DEPLOYMENT_TARGET=${{ inputs.deployment-target }} \
            -D CMAKE_IOS_INSTALL_COMBINED=NO \
            -D BABYLON_NATIVE_BUILD_APPS=OFF \
            -D BABYLON_DEBUG_TRACE=ON

      - name: Build
        run: cmake --build build/iOS --config RelWithDebInfo -- -sdk iphoneos CODE_SIGNING_ALLOWED=NO

      - name: Install
        run: cmake --install build/iOS --prefix=build/iOS/Install --config RelWithDebInfo
