name: Test Install macOS

on:
  workflow_call:
    inputs:
      xcode-version:
        required: false
        type: string
        default: '16.4'

jobs:
  test-install:
    runs-on: macos-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v5


      - name: Select Xcode ${{ inputs.xcode-version }}
        run: sudo xcode-select --switch /Applications/Xcode_${{ inputs.xcode-version }}.app/Contents/Developer

      - name: Configure
        run: |
          cmake -B build/macOS -G Xcode \
            -D BABYLON_NATIVE_BUILD_APPS=OFF \
            -D BABYLON_DEBUG_TRACE=ON

      - name: Build
        run: cmake --build build/macOS --config RelWithDebInfo

      - name: Install
        run: cmake --install build/macOS --prefix=build/macOS/Install --config RelWithDebInfo
