name: Test Install Linux

on:
  workflow_call: {}

env:
  CMAKE_VERSION: '3.31.6'

jobs:
  test-install:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-cmake
        with:
          cmake-version: ${{ env.CMAKE_VERSION }}

      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y libjavascriptcoregtk-4.1-dev libgl1-mesa-dev libcurl4-openssl-dev libwayland-dev

      - name: Configure
        run: |
          cmake -B build/Linux -G Ninja \
            -D CMAKE_BUILD_TYPE=RelWithDebInfo \
            -D BABYLON_NATIVE_BUILD_APPS=OFF \
            -D BABYLON_DEBUG_TRACE=ON

      - name: Build
        run: cmake --build build/Linux --config RelWithDebInfo

      - name: Install
        run: cmake --install build/Linux --prefix=build/Linux/Install --config=RelWithDebInfo
